# Generated by Django 4.0.4 on 2022-06-09 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amigos',
            name='nacimiento',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='nacimiento',
        ),
        migrations.RemoveField(
            model_name='familiares',
            name='nacimiento',
        ),
    ]
