# Generated by Django 4.0.4 on 2022-06-09 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_remove_amigos_nacimiento_remove_clientes_nacimiento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
